Minsal\CoreBundle\Entity\CatInsumo:
    type: entity
    table: cat_insumo
    indexes:
        ctl_insumo_nombre_largo_key:
            columns:
                - nombre_largo_insumo
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codigoNu:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: codigo_nu
        grupoid:
            type: integer
            nullable: true
            unsigned: false
        codigoSinab:
            type: string
            nullable: false
            length: 10
            fixed: false
            column: codigo_sinab
        listadoOficial:
            type: boolean
            nullable: true
            default: false
            column: listado_oficial
        nombreLargoInsumo:
            type: text
            nullable: true
            length: null
            fixed: false
            column: nombre_largo_insumo
        registroSchema:
            type: datetime
            nullable: true
            column: registro_schema
        enableSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: enable_schema
    manyToMany:
        trnDistribucion:
            targetEntity: TrnDistribucion
            cascade: {  }
            mappedBy: ctlInsumo
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
