Minsal\CoreBundle\Entity\TrnDetalle:
    type: entity
    table: trn_detalle
    indexes:
        IDX_D232DD2ABC0DA83B3CF50ACD:
            columns:
                - cat_productoid
                - trn_distribucionid
    uniqueConstraints:
        trn_detalle_id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        cpm:
            type: decimal
            nullable: false
            precision: 15
            scale: 2
        cantidadDistribuir:
            type: decimal
            nullable: false
            precision: 15
            scale: 2
            column: cantidad_distribuir
        cantidadSugerida:
            type: decimal
            nullable: false
            precision: 15
            scale: 2
            column: cantidad_sugerida
        existenciaAlmacenes:
            type: decimal
            nullable: false
            precision: 15
            scale: 2
            column: existencia_almacenes
        existenciaFarmacia:
            type: decimal
            nullable: false
            precision: 15
            scale: 2
            column: existencia_farmacia
        apiEstablecimientoid:
            type: integer
            nullable: false
            unsigned: false
            column: api_establecimientoid
        verificar:
            type: boolean
            nullable: true
        observacion:
            type: text
            nullable: true
            length: null
            fixed: false
        fechaCreacion:
            type: date
            nullable: false
            column: fecha_creacion
        fechaModificacion:
            type: date
            nullable: true
            column: fecha_modificacion
    manyToOne:
        catProductoid:
            targetEntity: DistribucionProducto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cat_productoid:
                    referencedColumnName: ctl_insumo_id
                trn_distribucionid:
                    referencedColumnName: trn_distribucion_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
