Minsal\CoreBundle\Entity\TrnEntregas:
    type: entity
    table: trn_entregas
    indexes:
        IDX_3CBBE8592830D723:
            columns:
                - trn_detalleid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        cantidadDistribuida:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: cantidad_distribuida
        fechaDocumento:
            type: date
            nullable: true
            column: fecha_documento
        fechaCreacion:
            type: date
            nullable: false
            column: fecha_creacion
        fechaModificacion:
            type: date
            nullable: true
            column: fecha_modificacion
    manyToOne:
        trnDetalleid:
            targetEntity: TrnDetalle
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                trn_detalleid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
