Minsal\CoreBundle\Entity\TrnProductoslote:
    type: entity
    table: trn_productoslote
    indexes:
        IDX_CEB5167482C53CF53CF50ACD:
            columns:
                - cat_isnumoid
                - trn_distribucionid
    id:
        apiLoteid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: api_loteid
            generator:
                strategy: SEQUENCE
    manyToOne:
        catIsnumoid:
            targetEntity: DistribucionProducto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cat_isnumoid:
                    referencedColumnName: ctl_insumo_id
                trn_distribucionid:
                    referencedColumnName: trn_distribucion_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
