minsal_reporte_homepage:
    path:     /inicio
    defaults: { _controller: MinsalCoreBundle:Reporte:index }

minsal_reporte_consumo_mensual:
    path:     /consumomensual
    defaults: { _controller: MinsalCoreBundle:ConsumoMensual:formularioConsumoMensual }

minsal_reporte_consumo_existencia:
    path:     /consumoexistencia
    defaults: { _controller: MinsalCoreBundle:ReporteExistencia:formularioExistencia }
