minsal_reporte_homepage:
    path:     /
    defaults: { _controller: MinsalReporteBundle:Default:index }

minsal_reportador:
    resource: "@MinsalReporteBundle/Resources/config/routing/Reporte/routing.yml"
    prefix:   /reporte
