minsal_core_trndistribucion:
    resource: "@MinsalCoreBundle/Resources/config/routing/Reporte/routing.yml"
    prefix:   /reportes

minsal_core_homepage:
    path:     /
    defaults: { _controller: MinsalCoreBundle:Default:index }
